### PR TITLE
upgraded library to v.0.5.10 because of an issue in v0.5.4

### PR DESCRIPTION
**Pull request by lzecca78**
In current library github.com/ulikunitz/xz v 0.5.4 there is the following issue: https://github.com/advisories/GHSA-25xm-hr59-7c27

### CODE REVIEW

**Review by ralgozino — APPROVED** [review]
I'm ok with having dependencies up to date.

For completeness, being that this one is an indirect dependency, can I ask what's the motivation to update it?
Do we have a reported bug or something we can link in fury agent that will be fixed by this PR?
Thanks!

**Comment by lzecca78** [comment]
hi @ralgozino, the issue was raised by the dependabot https://github.com/dependabot. For this reason, I've opened this PR. The reported bug is this: https://github.com/advisories/GHSA-25xm-hr59-7c27 as i wrote in the first message of the PR

**Review by angelbarrera92 — APPROVED** [review]
LGTM!

**Comment by ralgozino** [comment]
closing because the library is not used anymore on `main`

**Pull request closed without merging**
