### PR TITLE
Fix furyagent version command and bump version.

### LINKED ISSUE #10: furyagent version fails if there's no furyagent.yml file present
```shell
$ furyagent version
2020-02-27 18:17:25.996919 I | root.go:46: Error reading config using config file: furyagent.yml
```

### PR DESCRIPTION
**Pull request by ralgozino**
This PR fixes #10

### CODE REVIEW

**Comment by angelbarrera92** [comment]
The same error happened in the printDefault command, which does not make sense. The printDefault command was unimplemented so, it's better to remove it (this is why i have pushed this change)

**Comment by lnovara** [comment]
Can't we just move the `-config` flag only in the subcommands where it makes sens to have it? Or is the `PersistentPreRun` the standard way to address this kind of issues?

**Comment by ralgozino** [comment]
> Can't we just move the `-config` flag only in the subcommands where it makes sens to have it? Or is the `PersistentPreRun` the standard way to address this kind of issues?

The problem is not the flag, but the configuration file loading.

That was my intention at first but 99% of commands require the config loaded. `version` and `help` (that's "built-in") are the only ones that don't. In my opinion we can leave it like this, at least for the time being to solve this issue, a further global re-write is needed.

**Comment by lnovara** [comment]
I agree, it was more a curiosity of mine than a real issue. 😅

**Comment by lnovara** [comment]
@ralgozino can we handle the `version` package in `furyagent` in the same way as we do for `furyctl`? This way, we don't have to remember to manually bump the version when we release a new one.

Refs:
  - https://github.com/sighupio/furyctl/commit/62316ecb8c26287fd33b64fcb2968a9f4956e550
  - https://github.com/sighupio/furyctl/commit/6626c40264031055358efc13c48eebfe2098b190

**Comment by ralgozino** [comment]
Yep! I agree, we should totally use the same approach that we are using for `furyctl`

**Comment by angelbarrera92** [comment]
> Yep! I agree, we should totally use the same approach that we are using for `furyctl`
> 
> EDIT: I've just pushed the changes to use ldflags for the version just like in `furyctl`. Please @angelbarrera92 take a look into it :)

The ldflags looks good to me! Same for the rest of the PR! Awesome work!

**Pull request merged**
