### PR TITLE
Enable prerelease automatic detection

### PR DESCRIPTION
**Pull request by ralgozino**
Needed for https://github.com/sighupio/fury-kubernetes-aws/pull/35

### CODE REVIEW

**Comment by angelbarrera92** [comment]
Can you test it creating a new release candidate tag in this branch with the new version? Something like: v0.1.3-rc1

**Comment by ralgozino** [comment]
It works 😈 
image

**Comment by angelbarrera92** [comment]
Merging and releasing ;)

**Comment by ralgozino** [comment]
If you try to download latest:

```shell
$ curl https://github.com/sighupio/furyagent/releases/latest/download/furyagent-linux-amd64

<html><body>You are being <a href="https://github.com/sighupio/furyagent/releases/download/v0.1.2/furyagent-linux-amd64">redirected</a>.</body></html>%
```

You get redirected to 0v.1.2 :)

**Comment by angelbarrera92** [comment]
Awesome work @ralgozino  ;) a simple change can make a big different ;)

**Pull request merged**
